import serial, time, sys
arduino = serial.Serial('/dev/ttyACM0', 115200, timeout=.1)
time.sleep(1)
arduino.reset_input_buffer()
arduino.reset_output_buffer()
arduino.readlines()
print ("Running Test")
print ("    Low Test")
arduino.write('L')
time.sleep(0.1)
assert (arduino.readline().rstrip() == "Ok")
time.sleep(0.1)
arduino.write('RGY')
R = int(arduino.readline())
G = int(arduino.readline())
Y = int(arduino.readline())
print ("        R: {}    G: {}    Y: {}".format(R, G, Y))
if G > Y and G > R:
	print ("        [PASSED]")
else:
	sys.exit(1)
print ("    Mid Test")
arduino.write('M')
time.sleep(0.1)
assert (arduino.readline().rstrip() == "Ok")
time.sleep(0.1)
arduino.write('RGY')
R = int(arduino.readline())
G = int(arduino.readline())
Y = int(arduino.readline())
print ("        R: {}    G: {}    Y: {}".format(R, G, Y))
if Y > G and Y > R:
	print ("        [PASSED]")
else:
	sys.exit(1)
print ("    High Test")
arduino.write('H')
time.sleep(0.1)
assert (arduino.readline().rstrip() == "Ok")
time.sleep(0.1)
arduino.write('RGY')
R = int(arduino.readline())
G = int(arduino.readline())
Y = int(arduino.readline())
print ("        R: {}    G: {}    Y: {}".format(R, G, Y))
if R > Y and R > G:
	print ("        [PASSED]")
else:
	sys.exit(1)

sys.exit(0)
